language: node_js
node_js:
  - "node"
sudo: false
cache:
  directories:
    - node_modules
notifications:
  email: false
deploy:
  provider: npm
  email: "sbueringer@gmail.com"
  api_key: $NPM_API_KEY
  on:
    tags: true

